export const channelStatuses = {
  CHANNEL_OK: 'ok',
  CHANNEL_TIMEOUT: 'timeout',
  CHANNEL_ERROR: 'error',
  CHANNEL_JOINED: 'joined',
};

const base = '@trixta/phoenix-to-redux-event';
export const channelActionTypes = {
  CHANNEL_JOIN: `${base}/PHOENIX_CHANNEL_JOIN`,
  CHANNEL_LEAVE: `${base}/PHOENIX_CHANNEL_LEAVE`,
  CHANNEL_PUSH: `${base}/PHOENIX_CHANNEL_PUSH`,
  CHANNEL_CLOSE: `${base}/PHOENIX_CHANNEL_CLOSE`,
  CHANNEL_PUSH_ERROR: `${base}/PHOENIX_CHANNEL_PUSH_ERROR`,
  CHANNEL_JOIN_ERROR: `${base}/PHOENIX_CHANNEL_JOIN_ERROR`,
  CHANNEL_ERROR: `${base}/PHOENIX_CHANNEL_ERROR`,
  CHANNEL_TIMEOUT: `${base}/PHOENIX_CHANNEL_TIMEOUT`,
  CHANNEL_PRESENCE_LOG: `${base}/PHOENIX_CHANNEL_PRESENCE_LOG`,
  CHANNEL_UPDATED: `${base}/PHOENIX_CHANNEL_UPDATED`,
  CHANNEL_PRESENCE_UPDATE: `${base}/PHOENIX_CHANNEL_PRESENCE_UPDATE`,
  CHANNEL_PRESENCE_LEAVE: `${base}/PHOENIX_CHANNEL_PRESENCE_LEAVE`,
  CHANNEL_PRESENCE_JOIN: `${base}/PHOENIX_CHANNEL_PRESENCE_JOIN`,
  CHANNEL_PRESENCE_STATE: `${base}/PHOENIX_CHANNEL_PRESENCE_STATE`,
  CHANNEL_PRESENCE_CHANGE: `${base}/PHOENIX_CHANNEL_PRESENCE_CHANGE`,
};

export const phoenixChannelStatuses = {
  CHANNEL_OK: 'ok',
  CHANNEL_TIMEOUT: 'timeout',
  CHANNEL_PRESENCE_STATE: 'presence_state',
  CHANNEL_PRESENCE_CHANGE: 'presence_diff',
  CHANNEL_ERROR: 'error',
};
