export const socketActionTypes = {
  SOCKET_OPEN: 'PHOENIX_SOCKET_OPEN',
  SOCKET_CLOSE: 'PHOENIX_SOCKET_CLOSE',
  SOCKET_ERROR: 'PHOENIX_SOCKET_ERROR',
  SOCKET_CONNECT: 'PHOENIX_SOCKET_CONNECT',
  SOCKET_DISCONNECT: 'PHOENIX_SOCKET_DISCONNECT',
};

export const socketStatuses = {
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  OPEN: 'OPEN',
  CLOSING: 'CLOSING',
  CLOSED: 'CLOSED',
  DISCONNECTED: 'DISCONNECTED',
  ERROR: 'ERROR',
};

export const phoenixSocketStatuses = {
  CONNECTING: 0,
  OPEN: 1,
  CLOSING: 2,
  CLOSED: 3,
};
