name: publish-release

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  publish-release:
    name: Running release
    if:
      "contains(toJSON(github.event.commits.*.message), 'chore(release):')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    env:
      CI: true

    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: 🚀 Publish package to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@trixtateam'
      - run: yarn
      - run: yarn publish:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - if: always()
        run: rm .npmrc

      - name: 🚀 Publish package to NPM Registry
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@trixtateam'
      - run: yarn
      - run: yarn publish:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: always()
        run: rm .npmrc
